#!/bin/bash

#This script is a helpful tool for someone who finds themselves going to social
#media without even thinking when code is building, or some other non instantaneous
#operation has to be performed while coding.  

#Overcoming our weakness is how we become strong

HOSTS="/etc/hosts"
HOSTS_BACKUP="/etc/hosts.productive_mode.bak"

ENABLE_REDIRECTS=\
"www.facebook.com
www.reddit.com
www.youtube.com
www.instagram.com"

MARKER="#productive_mode"

##Changes -nice to haves
#   I would like to read the blocked sites from a config file
#   Add -e flag to enable individual websites

if [ ! -e $HOSTS_BACKUP ]; then
    echo "creating hosts backup"
    sudo cp $HOSTS $HOSTS_BACKUP
fi

if [ "$1" = "-d" ]; then
    echo "Removing redirects"
    sudo sed -iq "/${MARKER}/d" $HOSTS
else
    for i in $ENABLE_REDIRECTS;
    do
        echo "Adding line"
        echo "127.0.0.1 $i ${MARKER}" | sudo tee -a $HOSTS
    done
fi
