#!/bin/bash

#This script is a helpful tool for someone who finds themselves going to social
#media without even thinking when code is building, or some other non instantaneous
#operation has to be performed while coding.  

#Overcoming our weakness is how we become strong

HOSTS=./test

ENABLE_REDIRECTS=\
"www.facebook.com
www.reddit.com
www.youtube.com
www.instagram.com"

##Changes - I would like to read the blocked sites from a config file
#   Add -e flag to enable individual websites
#   Add check for existing entry to not interfere with entries in
#     /etc/hosts that may already exist

for i in $ENABLE_REDIRECTS;
do
    echo "127.0.0.1 $i #productive_mode" > HOSTS
done

if [ $1 == "--disable" ]
then
    sed -n '/#productive_mode_redirect/!p' file
fi
